# Generated by Django 4.2.8 on 2025-09-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('strain', 'Штамм'), ('sample', 'Образец'), ('storage', 'Хранилище')], max_length=20, verbose_name='Тип объекта')),
                ('object_id', models.IntegerField(verbose_name='ID объекта')),
                ('action', models.CharField(choices=[('CREATE', 'Создание'), ('UPDATE', 'Обновление'), ('DELETE', 'Удаление'), ('BULK_UPDATE', 'Массовое обновление'), ('BULK_DELETE', 'Массовое удаление')], max_length=20, verbose_name='Действие')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Старые значения')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Новые значения')),
                ('user_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пользователь')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('batch_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID массовой операции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Журнал изменений',
                'verbose_name_plural': 'Журнал изменений',
                'db_table': 'audit_changelog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='audit_changelog_content_idx'), models.Index(fields=['action'], name='audit_changelog_action_idx'), models.Index(fields=['created_at'], name='audit_changelog_created_idx'), models.Index(fields=['batch_id'], name='audit_changelog_batch_idx')],
            },
        ),
    ]
