# Generated by Django 4.2.8 on 2025-09-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=100, verbose_name='Короткий код штамма')),
                ('rrna_taxonomy', models.CharField(blank=True, max_length=200, null=True, verbose_name='rRNA таксономия')),
                ('identifier', models.CharField(max_length=200, verbose_name='Идентификатор штамма')),
                ('name_alt', models.CharField(blank=True, max_length=200, null=True, verbose_name='Альтернативное название')),
                ('rcam_collection_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID коллекции RCAM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Штамм',
                'verbose_name_plural': 'Штаммы',
                'ordering': ['short_code'],
            },
        ),
    ]
