# Generated by Django 4.2.8 on 2025-09-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmylaseVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название варианта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вариант амилазы',
                'verbose_name_plural': 'Варианты амилазы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GrowthMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название среды роста')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Среда роста',
                'verbose_name_plural': 'Среды роста',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IndexLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_value', models.CharField(max_length=10, unique=True, verbose_name='Индексная буква')),
            ],
            options={
                'verbose_name': 'Индексная буква',
                'verbose_name_plural': 'Индексные буквы',
                'ordering': ['letter_value'],
            },
        ),
        migrations.CreateModel(
            name='IUKColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название цвета')),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='HEX код цвета')),
            ],
            options={
                'verbose_name': 'Цвет ИУК',
                'verbose_name_plural': 'Цвета ИУК',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название местоположения')),
            ],
            options={
                'verbose_name': 'Местоположение',
                'verbose_name_plural': 'Местоположения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism_name', models.CharField(max_length=300, verbose_name='Название организма')),
                ('source_type', models.CharField(max_length=100, verbose_name='Тип источника')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ['organism_name'],
            },
        ),
    ]
