# Generated by Django 5.2.6 on 2025-09-28 02:40

from django.db import migrations, models
import django.db.models.deletion


def populate_source_relations(apps, schema_editor):
    Source = apps.get_model('reference_data', 'Source')
    SourceType = apps.get_model('reference_data', 'SourceType')
    SourceCategory = apps.get_model('reference_data', 'SourceCategory')

    # Создаем значения по умолчанию, если встречаются пустые поля
    default_type, _ = SourceType.objects.get_or_create(name='Не указан')
    default_category, _ = SourceCategory.objects.get_or_create(name='Не указана')

    # Сначала создаем уникальные типы и категории
    for type_name in (
        Source.objects.exclude(source_type__isnull=True)
        .exclude(source_type__exact='')
        .values_list('source_type', flat=True)
        .distinct()
    ):
        SourceType.objects.get_or_create(name=type_name.strip())

    for category_name in (
        Source.objects.exclude(category__isnull=True)
        .exclude(category__exact='')
        .values_list('category', flat=True)
        .distinct()
    ):
        SourceCategory.objects.get_or_create(name=category_name.strip())

    # Теперь привязываем источники к новым справочникам
    for source in Source.objects.all():
        type_name = (source.source_type or '').strip()
        category_name = (source.category or '').strip()

        if type_name:
            source_type_obj = SourceType.objects.get(name=type_name)
        else:
            source_type_obj = default_type

        if category_name:
            category_obj = SourceCategory.objects.get(name=category_name)
        else:
            category_obj = default_category

        source.source_type_new_id = source_type_obj.id
        source.category_new_id = category_obj.id
        source.save(update_fields=['source_type_new', 'category_new'])


def reverse_populate_source_relations(apps, schema_editor):
    Source = apps.get_model('reference_data', 'Source')
    SourceType = apps.get_model('reference_data', 'SourceType')
    SourceCategory = apps.get_model('reference_data', 'SourceCategory')

    for source in Source.objects.select_related('source_type_new', 'category_new'):
        source.source_type = source.source_type_new.name if source.source_type_new else ''
        source.category = source.category_new.name if source.category_new else ''
        source.save(update_fields=['source_type', 'category'])

    # Не удаляем записи справочников при откате — они могут использоваться повторно


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0003_auto_20250924_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория источника',
                'verbose_name_plural': 'Категории источников',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа источника')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип источника',
                'verbose_name_plural': 'Типы источников',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='source',
            name='category_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reference_data.sourcecategory', verbose_name='Категория (временное поле)'),
        ),
        migrations.AddField(
            model_name='source',
            name='source_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reference_data.sourcetype', verbose_name='Тип источника (временное поле)'),
        ),
        migrations.RunPython(populate_source_relations, reverse_populate_source_relations),
        migrations.RemoveField(
            model_name='source',
            name='category',
        ),
        migrations.RemoveField(
            model_name='source',
            name='source_type',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='category_new',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='source_type_new',
            new_name='source_type',
        ),
        migrations.AlterField(
            model_name='source',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='reference_data.sourcecategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='reference_data.sourcetype', verbose_name='Тип источника'),
        ),
    ]
