version: '3.8'

services:
  # =============================================================================
  # PostgreSQL Database для разработки
  # =============================================================================
  postgres:
    image: postgres:14
    container_name: strain_postgres_dev
    environment:
      POSTGRES_DB: strain_collection
      POSTGRES_USER: strain_user
      POSTGRES_PASSWORD: strain_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./backend/collection_manager/management/commands:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U strain_user -d strain_collection"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - strain_network_dev
    restart: unless-stopped

  # =============================================================================
  # pgAdmin для удобства разработки (опционально)
  # =============================================================================
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: strain_pgadmin_dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@strain.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - strain_network_dev
    restart: unless-stopped
    profiles: ["tools"]  # Запускается только при --profile tools

volumes:
  postgres_data_dev:
    driver: local
  pgadmin_data_dev:
    driver: local

networks:
  strain_network_dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 