# Generated by Django 4.2.7 on 2025-06-19 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("collection_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="storage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="collection_manager.storage",
                verbose_name="Место хранения",
            ),
        ),
    ]
