# Generated by Django 4.2.7 on 2025-06-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection_manager", "0003_add_search_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("strain", "Штамм"),
                            ("sample", "Образец"),
                            ("storage", "Хранилище"),
                        ],
                        max_length=20,
                        verbose_name="Тип объекта",
                    ),
                ),
                ("object_id", models.IntegerField(verbose_name="ID объекта")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Создание"),
                            ("UPDATE", "Обновление"),
                            ("DELETE", "Удаление"),
                            ("BULK_UPDATE", "Массовое обновление"),
                            ("BULK_DELETE", "Массовое удаление"),
                        ],
                        max_length=20,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Старые значения"
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Новые значения"
                    ),
                ),
                (
                    "user_info",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ID массовой операции",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал изменений",
                "verbose_name_plural": "Журнал изменений",
                "db_table": "changelog",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="changelog_content_f91483_idx",
                    ),
                    models.Index(fields=["action"], name="changelog_action_4ecf66_idx"),
                    models.Index(
                        fields=["created_at"], name="changelog_created_6385bc_idx"
                    ),
                    models.Index(
                        fields=["batch_id"], name="changelog_batch_i_8c30c5_idx"
                    ),
                ],
            },
        ),
    ]
