# Generated by Django 4.2.23 on 2025-07-01 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection_manager", "0004_create_changelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "box_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="ID бокса"
                    ),
                ),
                ("rows", models.PositiveIntegerField(verbose_name="Количество рядов")),
                (
                    "cols",
                    models.PositiveIntegerField(verbose_name="Количество колонок"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Бокс",
                "verbose_name_plural": "Боксы",
                "ordering": ["box_id"],
            },
        ),
        migrations.AlterField(
            model_name="storage",
            name="cell_id",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ячейка должна быть в формате букваA-Z + номер 1-99 (например A1, B12)",
                        regex="^[A-Z][0-9]{1,2}$",
                    )
                ],
                verbose_name="ID ячейки",
            ),
        ),
    ]
