# Generated by Django 4.2.23 on 2025-07-01 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("collection_manager", "0005_storagebox_alter_storage_cell_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SamplePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="samples/%Y/%m/%d/", verbose_name="Изображение"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="collection_manager.sample",
                        verbose_name="Образец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография образца",
                "verbose_name_plural": "Фотографии образцов",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
