# Generated by Django 4.2.7 on 2025-08-29 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("collection_manager", "0006_samplephoto"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrowthMedium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Название среды роста"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание среды"
                    ),
                ),
            ],
            options={
                "verbose_name": "Среда роста",
                "verbose_name_plural": "Среды роста",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="sample",
            name="amylase_variant",
            field=models.CharField(
                blank=True,
                help_text="Тип или вариант вырабатываемой амилазы",
                max_length=100,
                null=True,
                verbose_name="Вариант амилазы",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="appendix_note_text",
            field=models.TextField(
                blank=True,
                help_text="Произвольный текст примечания",
                null=True,
                verbose_name="Примечание",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="comment_text",
            field=models.TextField(
                blank=True,
                help_text="Произвольный текст комментария",
                null=True,
                verbose_name="Комментарий",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="iuk_color",
            field=models.CharField(
                blank=True,
                help_text="Цвет, который приобретает среда при выработке ИУК",
                max_length=100,
                null=True,
                verbose_name="Цвет окраски ИУК",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="mobilizes_phosphates",
            field=models.BooleanField(default=False, verbose_name="Мобилизует фосфаты"),
        ),
        migrations.AddField(
            model_name="sample",
            name="produces_amylase",
            field=models.BooleanField(
                default=False, verbose_name="Вырабатывает амилазу"
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="produces_iuk",
            field=models.BooleanField(default=False, verbose_name="Вырабатывает ИУК"),
        ),
        migrations.AddField(
            model_name="sample",
            name="produces_siderophores",
            field=models.BooleanField(
                default=False, verbose_name="Вырабатывает сидерофоры"
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="stains_medium",
            field=models.BooleanField(default=False, verbose_name="Окрашивает среду"),
        ),
        migrations.AlterField(
            model_name="sample",
            name="appendix_note",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="collection_manager.appendixnote",
                verbose_name="Примечание (устаревшее поле)",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="collection_manager.comment",
                verbose_name="Комментарий (устаревшее поле)",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="growth_media_ids",
            field=models.ManyToManyField(
                blank=True,
                help_text="Выберите среды роста для данного образца",
                to="collection_manager.growthmedium",
                verbose_name="Среды роста",
            ),
        ),
    ]
