# Generated by Django 4.2.7 on 2025-09-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection_manager", "0006_samplephoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="appendix_note",
            field=models.TextField(blank=True, null=True, verbose_name="Примечание"),
        ),
        migrations.AlterField(
            model_name="sample",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
    ]
