# Generated by Django 4.2.7 on 2025-09-02 04:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collection_manager", "0007_alter_sample_appendix_note_alter_sample_comment"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE collection_manager_sample DROP COLUMN IF EXISTS mobilizes_phosphates; ALTER TABLE collection_manager_sample DROP COLUMN IF EXISTS produces_amylase;",
            reverse_sql="ALTER TABLE collection_manager_sample ADD COLUMN mobilizes_phosphates BOOLEAN DEFAULT false NOT NULL;"
        ),
    ]
