# Generated by Django 4.2.7 on 2025-09-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collection_manager", "0008_auto_20250902_0738"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE collection_manager_sample DROP COLUMN IF EXISTS mobilizes_phosphates; ALTER TABLE collection_manager_sample DROP COLUMN IF EXISTS produces_amylase; ALTER TABLE collection_manager_sample DROP COLUMN IF EXISTS produces_iuk;",
            reverse_sql="ALTER TABLE collection_manager_sample ADD COLUMN mobilizes_phosphates BOOLEAN DEFAULT false NOT NULL; ALTER TABLE collection_manager_sample ADD COLUMN produces_amylase BOOLEAN DEFAULT false NOT NULL;"
        ),
    ]
