# Generated by Django 4.2.7 on 2025-09-02 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collection_manager", "0009_fix_db_sync"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE collection_manager_sample DROP COLUMN IF EXISTS produces_iuk; ALTER TABLE collection_manager_sample DROP COLUMN IF EXISTS produces_siderophores;",
            reverse_sql="ALTER TABLE collection_manager_sample ADD COLUMN produces_iuk BOOLEAN DEFAULT false NOT NULL;"
        ),
    ]
