# Generated by Django 4.2.7 on 2025-09-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collection_manager", "0010_fix_db_sync2"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE collection_manager_sample DROP COLUMN IF EXISTS produces_siderophores;",
            reverse_sql="ALTER TABLE collection_manager_sample ADD COLUMN produces_siderophores BOOLEAN DEFAULT false NOT NULL;"
        ),
    ]
