# Generated by Django 4.2.7 on 2025-09-02 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collection_manager", "0011_fix_db_sync3"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE collection_manager_sample 
            DROP COLUMN IF EXISTS amylase_variant,
            DROP COLUMN IF EXISTS appendix_note_text,
            DROP COLUMN IF EXISTS comment_text,
            DROP COLUMN IF EXISTS iuk_color,
            DROP COLUMN IF EXISTS stains_medium;
            """,
            reverse_sql="""
            ALTER TABLE collection_manager_sample 
            ADD COLUMN amylase_variant VARCHAR(100),
            ADD COLUMN appendix_note_text TEXT,
            ADD COLUMN comment_text TEXT,
            ADD COLUMN iuk_color VARCHAR(50),
            ADD COLUMN stains_medium BOOLEAN DEFAULT false;
            """
        ),
    ]
