# Generated by Django 4.2.7 on 2025-09-02 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("collection_manager", "0012_remove_extra_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name='AmylaseVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название варианта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вариант амилазы',
                'verbose_name_plural': 'Варианты амилазы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IUKColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название цвета')),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='HEX код цвета')),
            ],
            options={
                'verbose_name': 'Цвет ИУК',
                'verbose_name_plural': 'Цвета ИУК',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='amylase_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection_manager.amylasevariant', verbose_name='Вариант амилазы'),
        ),
        migrations.AddField(
            model_name='sample',
            name='iuk_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection_manager.iukcolor', verbose_name='Цвет окраски ИУК'),
        ),
        migrations.AddField(
            model_name='sample',
            name='mobilizes_phosphates',
            field=models.BooleanField(default=False, verbose_name='Мобилизирует фосфаты'),
        ),
        migrations.AddField(
            model_name='sample',
            name='produces_siderophores',
            field=models.BooleanField(default=False, verbose_name='Вырабатывает сидерофоры'),
        ),
        migrations.AddField(
            model_name='sample',
            name='stains_medium',
            field=models.BooleanField(default=False, verbose_name='Окрашивает среду'),
        ),
    ]
