# Generated by Django 4.2.7 on 2025-09-02 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collection_manager", "0013_add_missing_models_and_fields"),
    ]

    operations = []
