version: '3.8'

services:
  db:
    image: postgres:14
    container_name: strain_tracker_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: strain_tracker
      POSTGRES_USER: strain_user
      POSTGRES_PASSWORD: strain_password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
    networks:
      - strain_network

volumes:
  postgres_data:

networks:
  strain_network:
    driver: bridge 