# Generated by Django 4.2.8 on 2025-09-23 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage_management', '0001_initial'),
        ('strain_management', '0001_initial'),
        ('reference_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_sample_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Оригинальный номер образца')),
                ('appendix_note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('has_photo', models.BooleanField(default=False, verbose_name='Есть фото')),
                ('is_identified', models.BooleanField(default=False, verbose_name='Идентифицирован')),
                ('has_antibiotic_activity', models.BooleanField(default=False, verbose_name='Есть антибиотическая активность')),
                ('has_genome', models.BooleanField(default=False, verbose_name='Есть геном')),
                ('has_biochemistry', models.BooleanField(default=False, verbose_name='Есть биохимия')),
                ('seq_status', models.BooleanField(default=False, verbose_name='Статус секвенирования')),
                ('mobilizes_phosphates', models.BooleanField(default=False, verbose_name='Мобилизирует фосфаты')),
                ('stains_medium', models.BooleanField(default=False, verbose_name='Окрашивает среду')),
                ('produces_siderophores', models.BooleanField(default=False, verbose_name='Вырабатывает сидерофоры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('amylase_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference_data.amylasevariant', verbose_name='Вариант амилазы')),
                ('index_letter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference_data.indexletter', verbose_name='Индексная буква')),
                ('iuk_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference_data.iukcolor', verbose_name='Цвет окраски ИУК')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference_data.location', verbose_name='Местоположение')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference_data.source', verbose_name='Источник')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage_management.storage', verbose_name='Место хранения')),
                ('strain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='strain_management.strain', verbose_name='Штамм')),
            ],
            options={
                'verbose_name': 'Образец',
                'verbose_name_plural': 'Образцы',
                'ordering': ['strain__short_code', 'original_sample_number'],
            },
        ),
        migrations.CreateModel(
            name='SamplePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='samples/%Y/%m/%d/', verbose_name='Изображение')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sample_management.sample', verbose_name='Образец')),
            ],
            options={
                'verbose_name': 'Фотография образца',
                'verbose_name_plural': 'Фотографии образцов',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleGrowthMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_medium', models.ForeignKey(db_column='growthmedium_id', on_delete=django.db.models.deletion.CASCADE, to='reference_data.growthmedium', verbose_name='Среда роста')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_media', to='sample_management.sample', verbose_name='Образец')),
            ],
            options={
                'verbose_name': 'Среда роста образца',
                'verbose_name_plural': 'Среды роста образцов',
                'db_table': 'sample_growth_media',
                'unique_together': {('sample', 'growth_medium')},
            },
        ),
    ]
